name: Main
on: [push]
jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - uses: borales/actions-yarn@v2.3.0
        name: Install Node modules
        with:
          cmd: --cwd frontend_react install # will run `yarn install` command
      - uses: borales/actions-yarn@v2.3.0
        name: Run Unit Test
        with:
          cmd: --cwd frontend_react test # will run `yarn test` command
